import { School, SchoolType, Wilayat, Gender, Shift } from './types';

// Seed Data - Comprehensive List based on Phase 3 Data
export const schoolsData: School[] = [
  // =================================================================
  // مدارس حكومية - صلالة
  // =================================================================
  {
    id: "8101",
    name: "مدرسة ظفار للتعليم الأساسي",
    wilayat: Wilayat.SALALAH,
    area: "السعادة", // Updated location
    type: SchoolType.GOVERNMENT,
    grades: "10-12",
    gender: Gender.BOYS,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0585, lng: 54.1560 }, // Updated coordinates for Al Saada
    contact: { managerName: "محمد الهزيلي", phone: "23290001" }, // Updated Manager
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 5
  },
  {
    id: "8102",
    name: "مدرسة النور للتعليم الأساسي",
    wilayat: Wilayat.SALALAH,
    area: "صلالة الغربية",
    type: SchoolType.GOVERNMENT,
    grades: "5-10",
    gender: Gender.GIRLS,
    shift: Shift.MORNING,
    contact: { managerName: "فاطمة القرشي", phone: "23290003" },
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 4,
    coordinates: { lat: 17.0120, lng: 54.0850 }
  },
  {
    id: "8103",
    name: "المدرسة السعيدية بصلالة",
    wilayat: Wilayat.SALALAH,
    area: "صلالة",
    type: SchoolType.GOVERNMENT,
    grades: "10-12",
    gender: Gender.BOYS,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0150, lng: 54.0920 },
    contact: { managerName: "محمد الواردي", phone: "23290002" },
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 5
  },
  {
    id: "8104",
    name: "مدرسة الخريف للتعليم الأساسي",
    wilayat: Wilayat.SALALAH,
    area: "صلالة",
    type: SchoolType.GOVERNMENT,
    grades: "1-4",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0220, lng: 54.1000 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8105",
    name: "مدرسة السلطان تيمور بن فيصل",
    wilayat: Wilayat.SALALAH,
    area: "الدهاريز",
    type: SchoolType.GOVERNMENT,
    grades: "5-9",
    gender: Gender.BOYS,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0350, lng: 54.1200 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 4
  },
  {
    id: "8106",
    name: "مدرسة أسامة بن زيد",
    wilayat: Wilayat.SALALAH,
    area: "عوقد الجنوبية",
    type: SchoolType.GOVERNMENT,
    grades: "5-9",
    gender: Gender.BOYS,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0250, lng: 54.0450 },
    source: "وزارة التربية والتعليم",
    isVerified: true,
    contact: {},
    qualityScore: 3
  },
  {
    id: "8108",
    name: "مدرسة العوقدين للتعليم الأساسي",
    wilayat: Wilayat.SALALAH,
    area: "عوقد",
    type: SchoolType.GOVERNMENT,
    grades: "1-4",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0280, lng: 54.0420 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8109",
    name: "مدرسة خالد بن الوليد",
    wilayat: Wilayat.SALALAH,
    area: "الدهاريز",
    type: SchoolType.GOVERNMENT,
    grades: "5-9",
    gender: Gender.BOYS,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0380, lng: 54.1250 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8110",
    name: "مدرسة صلالة للتعليم الأساسي",
    wilayat: Wilayat.SALALAH,
    area: "صلالة",
    type: SchoolType.GOVERNMENT,
    grades: "10-12",
    gender: Gender.BOYS,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0190, lng: 54.0960 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 4
  },
  {
    id: "8111",
    name: "مدرسة الشعلة",
    wilayat: Wilayat.SALALAH,
    area: "عوقد",
    type: SchoolType.GOVERNMENT,
    grades: "5-9",
    gender: Gender.BOYS,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0300, lng: 54.0500 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8112",
    name: "مدرسة البدائع",
    wilayat: Wilayat.SALALAH,
    area: "صلالة",
    type: SchoolType.GOVERNMENT,
    grades: "1-4",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0140, lng: 54.0880 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8113",
    name: "مدرسة أنس بن مالك",
    wilayat: Wilayat.SALALAH,
    area: "صلالة",
    type: SchoolType.GOVERNMENT,
    grades: "5-9",
    gender: Gender.BOYS,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0210, lng: 54.0930 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8114",
    name: "مدرسة الكواكب",
    wilayat: Wilayat.SALALAH,
    area: "صلالة",
    type: SchoolType.GOVERNMENT,
    grades: "1-4",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0170, lng: 54.0900 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8115",
    name: "مدرسة أضبيدوت",
    wilayat: Wilayat.SALALAH,
    area: "الجبل",
    type: SchoolType.GOVERNMENT,
    grades: "5-12",
    gender: Gender.BOYS,
    shift: Shift.MORNING,
    coordinates: { lat: 17.1200, lng: 54.0500 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8116",
    name: "مدرسة الكنوز",
    wilayat: Wilayat.SALALAH,
    area: "صلالة",
    type: SchoolType.GOVERNMENT,
    grades: "1-4",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0130, lng: 54.0820 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8117",
    name: "مدرسة غدو للبنين",
    wilayat: Wilayat.SALALAH,
    area: "نيابة غدو",
    type: SchoolType.GOVERNMENT,
    grades: "5-12",
    gender: Gender.BOYS,
    shift: Shift.MORNING,
    coordinates: { lat: 17.1400, lng: 54.0600 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8118",
    name: "مدرسة غدو للبنات",
    wilayat: Wilayat.SALALAH,
    area: "نيابة غدو",
    type: SchoolType.GOVERNMENT,
    grades: "1-12",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.1420, lng: 54.0620 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8119",
    name: "مدرسة القنطرة",
    wilayat: Wilayat.SALALAH,
    area: "صلالة",
    type: SchoolType.GOVERNMENT,
    grades: "5-9",
    gender: Gender.BOYS,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0260, lng: 54.1100 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8120",
    name: "مدرسة منبع الحكمة",
    wilayat: Wilayat.SALALAH,
    area: "صلالة",
    type: SchoolType.GOVERNMENT,
    grades: "5-10",
    gender: Gender.GIRLS,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0280, lng: 54.1150 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 4
  },
  {
    id: "8121",
    name: "مدرسة صلالة الشرقية",
    wilayat: Wilayat.SALALAH,
    area: "صلالة الشرقية",
    type: SchoolType.GOVERNMENT,
    grades: "5-10",
    gender: Gender.BOYS,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0180, lng: 54.1050 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8122",
    name: "مدرسة صحلنوت",
    wilayat: Wilayat.SALALAH,
    area: "صحلنوت",
    type: SchoolType.GOVERNMENT,
    grades: "1-4",
    gender: Gender.MIXED,
    shift: Shift.EVENING,
    coordinates: { lat: 17.0650, lng: 54.1700 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8123",
    name: "مدرسة الأجيال",
    wilayat: Wilayat.SALALAH,
    area: "صلالة",
    type: SchoolType.GOVERNMENT,
    grades: "1-4",
    gender: Gender.MIXED,
    shift: Shift.EVENING,
    coordinates: { lat: 17.0200, lng: 54.0900 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8127",
    name: "مدرسة صلالة الجديدة",
    wilayat: Wilayat.SALALAH,
    area: "صلالة الجديدة",
    type: SchoolType.GOVERNMENT,
    grades: "1-4",
    gender: Gender.MIXED,
    shift: Shift.EVENING,
    coordinates: { lat: 17.0100, lng: 54.0800 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8129",
    name: "مدرسة الوادي",
    wilayat: Wilayat.SALALAH,
    area: "الوادي",
    type: SchoolType.GOVERNMENT,
    grades: "1-4",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0300, lng: 54.0700 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8131",
    name: "مدرسة محمد بن القاسم الثقفي",
    wilayat: Wilayat.SALALAH,
    area: "صلالة",
    type: SchoolType.GOVERNMENT,
    grades: "5-9",
    gender: Gender.BOYS,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0320, lng: 54.0750 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8133",
    name: "مدرسة السعادة للبنات",
    wilayat: Wilayat.SALALAH,
    area: "السعادة",
    type: SchoolType.GOVERNMENT,
    grades: "10-12",
    gender: Gender.GIRLS,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0550, lng: 54.1500 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 4
  },
  {
    id: "8136",
    name: "مدرسة الراية",
    wilayat: Wilayat.SALALAH,
    area: "صلالة",
    type: SchoolType.GOVERNMENT,
    grades: "5-9",
    gender: Gender.GIRLS,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0230, lng: 54.0980 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8137",
    name: "مدرسة 23 يوليو للبنات",
    wilayat: Wilayat.SALALAH,
    area: "صلالة",
    type: SchoolType.GOVERNMENT,
    grades: "5-10",
    gender: Gender.GIRLS,
    shift: Shift.EVENING,
    coordinates: { lat: 17.0160, lng: 54.0910 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8139",
    name: "مدرسة فاطمة الزهراء",
    wilayat: Wilayat.SALALAH,
    area: "الحصيلة",
    type: SchoolType.GOVERNMENT,
    grades: "7-10",
    gender: Gender.GIRLS,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0250, lng: 54.1100 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8141",
    name: "مدرسة عائشة بنت أبي بكر",
    wilayat: Wilayat.SALALAH,
    area: "صلالة",
    type: SchoolType.GOVERNMENT,
    grades: "5-10",
    gender: Gender.GIRLS,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0280, lng: 54.1050 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 4
  },
  {
    id: "8143",
    name: "مدرسة النهضة",
    wilayat: Wilayat.SALALAH,
    area: "صلالة",
    type: SchoolType.GOVERNMENT,
    grades: "11-12",
    gender: Gender.GIRLS,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0300, lng: 54.1200 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 4
  },
  {
    id: "8145",
    name: "مدرسة القرض",
    wilayat: Wilayat.SALALAH,
    area: "القرض",
    type: SchoolType.GOVERNMENT,
    grades: "1-4",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0450, lng: 54.1350 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8147",
    name: "مدرسة أم سليم الأنصارية",
    wilayat: Wilayat.SALALAH,
    area: "عوقد الشمالية",
    type: SchoolType.GOVERNMENT,
    grades: "5-9",
    gender: Gender.GIRLS,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0320, lng: 54.0480 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8148",
    name: "مدرسة المعتزة",
    wilayat: Wilayat.SALALAH,
    area: "صلالة",
    type: SchoolType.GOVERNMENT,
    grades: "1-4",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0200, lng: 54.0950 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8149",
    name: "مدرسة القوف",
    wilayat: Wilayat.SALALAH,
    area: "القوف",
    type: SchoolType.GOVERNMENT,
    grades: "1-4",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0250, lng: 54.1000 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8151",
    name: "مدرسة المروج للبنات",
    wilayat: Wilayat.SALALAH,
    area: "إتين",
    type: SchoolType.GOVERNMENT,
    grades: "5-9",
    gender: Gender.GIRLS,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0420, lng: 54.0720 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8152",
    name: "مدرسة المعرفة",
    wilayat: Wilayat.SALALAH,
    area: "صلالة",
    type: SchoolType.GOVERNMENT,
    grades: "1-4",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0280, lng: 54.0980 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8155",
    name: "مدرسة صلالة الغربية",
    wilayat: Wilayat.SALALAH,
    area: "صلالة الغربية",
    type: SchoolType.GOVERNMENT,
    grades: "1-4",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0100, lng: 54.0800 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8157",
    name: "مدرسة عوقد",
    wilayat: Wilayat.SALALAH,
    area: "عوقد",
    type: SchoolType.GOVERNMENT,
    grades: "5-6",
    gender: Gender.GIRLS,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0310, lng: 54.0510 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8158",
    name: "مدرسة القبس",
    wilayat: Wilayat.SALALAH,
    area: "صلالة",
    type: SchoolType.GOVERNMENT,
    grades: "1-4",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0220, lng: 54.0920 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8159",
    name: "مدرسة ناشب للبنين",
    wilayat: Wilayat.SALALAH,
    area: "ناشب",
    type: SchoolType.GOVERNMENT,
    grades: "5-12",
    gender: Gender.BOYS,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0800, lng: 54.1800 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8160",
    name: "مدرسة ناشب للبنات",
    wilayat: Wilayat.SALALAH,
    area: "ناشب",
    type: SchoolType.GOVERNMENT,
    grades: "1-12",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0820, lng: 54.1820 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8161",
    name: "مدرسة زيك للبنين",
    wilayat: Wilayat.SALALAH,
    area: "نيابة زيك",
    type: SchoolType.GOVERNMENT,
    grades: "5-12",
    gender: Gender.BOYS,
    shift: Shift.MORNING,
    coordinates: { lat: 17.1820, lng: 54.0220 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8162",
    name: "مدرسة زيك",
    wilayat: Wilayat.SALALAH,
    area: "نيابة زيك",
    type: SchoolType.GOVERNMENT,
    grades: "1-4",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.1800, lng: 54.0200 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8163",
    name: "مدرسة حجيف",
    wilayat: Wilayat.SALALAH,
    area: "نيابة حجيف",
    type: SchoolType.GOVERNMENT,
    grades: "5-12",
    gender: Gender.BOYS,
    shift: Shift.MORNING,
    coordinates: { lat: 17.2000, lng: 54.0400 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8164",
    name: "مدرسة قيرون حيريتي",
    wilayat: Wilayat.SALALAH,
    area: "نيابة قيرون حيريتي",
    type: SchoolType.GOVERNMENT,
    grades: "1-12",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.1500, lng: 54.0800 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8167",
    name: "مدرسة شير",
    wilayat: Wilayat.SALALAH,
    area: "شير",
    type: SchoolType.GOVERNMENT,
    grades: "5-12",
    gender: Gender.GIRLS,
    shift: Shift.MORNING,
    coordinates: { lat: 17.1000, lng: 54.1200 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8169",
    name: "مدرسة ريسوت للبنين",
    wilayat: Wilayat.SALALAH,
    area: "ريسوت",
    type: SchoolType.GOVERNMENT,
    grades: "5-12",
    gender: Gender.BOYS,
    shift: Shift.MORNING,
    coordinates: { lat: 16.9800, lng: 54.0300 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8170",
    name: "مدرسة ريسوت للبنات",
    wilayat: Wilayat.SALALAH,
    area: "ريسوت",
    type: SchoolType.GOVERNMENT,
    grades: "1-12",
    gender: Gender.GIRLS,
    shift: Shift.MORNING,
    coordinates: { lat: 16.9820, lng: 54.0320 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8171",
    name: "مدرسة عدونب",
    wilayat: Wilayat.SALALAH,
    area: "عدونب",
    type: SchoolType.GOVERNMENT,
    grades: "1-10",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0000, lng: 53.9500 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8173",
    name: "مدرسة طيطام للبنين",
    wilayat: Wilayat.SALALAH,
    area: "نيابة طيطام",
    type: SchoolType.GOVERNMENT,
    grades: "5-12",
    gender: Gender.BOYS,
    shift: Shift.MORNING,
    coordinates: { lat: 17.1000, lng: 53.9500 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8174",
    name: "مدرسة طيطام",
    wilayat: Wilayat.SALALAH,
    area: "نيابة طيطام",
    type: SchoolType.GOVERNMENT,
    grades: "1-12",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.1020, lng: 53.9520 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8175",
    name: "مدرسة قيرون حيريتي للبنين",
    wilayat: Wilayat.SALALAH,
    area: "نيابة قيرون حيريتي",
    type: SchoolType.GOVERNMENT,
    grades: "5-9",
    gender: Gender.BOYS,
    shift: Shift.MORNING,
    coordinates: { lat: 17.1520, lng: 54.0820 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8177",
    name: "مدرسة ألسان للبنين",
    wilayat: Wilayat.SALALAH,
    area: "ألسان",
    type: SchoolType.GOVERNMENT,
    grades: "5-12",
    gender: Gender.BOYS,
    shift: Shift.MORNING,
    coordinates: { lat: 17.2200, lng: 54.1500 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8178",
    name: "مدرسة ألسان",
    wilayat: Wilayat.SALALAH,
    area: "ألسان",
    type: SchoolType.GOVERNMENT,
    grades: "1-12",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.2220, lng: 54.1520 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8180",
    name: "مدرسة نحيز",
    wilayat: Wilayat.SALALAH,
    area: "نحيز",
    type: SchoolType.GOVERNMENT,
    grades: "1-10",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.1300, lng: 54.0900 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8183",
    name: "مدرسة وادي عين",
    wilayat: Wilayat.SALALAH,
    area: "وادي عين",
    type: SchoolType.GOVERNMENT,
    grades: "1-9",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.1600, lng: 54.2000 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8185",
    name: "مدرسة اصطاح للبنين",
    wilayat: Wilayat.SALALAH,
    area: "اصطاح",
    type: SchoolType.GOVERNMENT,
    grades: "5-10",
    gender: Gender.BOYS,
    shift: Shift.EVENING,
    coordinates: { lat: 17.0700, lng: 54.1400 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8186",
    name: "مدرسة اصطاح",
    wilayat: Wilayat.SALALAH,
    area: "اصطاح",
    type: SchoolType.GOVERNMENT,
    grades: "1-9",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0720, lng: 54.1420 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8187",
    name: "مدرسة قفطوت",
    wilayat: Wilayat.SALALAH,
    area: "قفطوت",
    type: SchoolType.GOVERNMENT,
    grades: "1-10",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.2500, lng: 53.9800 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8189",
    name: "مدرسة ركبيت",
    wilayat: Wilayat.SALALAH,
    area: "ركبيت",
    type: SchoolType.GOVERNMENT,
    grades: "5-10",
    gender: Gender.BOYS,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0900, lng: 54.2500 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8193",
    name: "مدرسة أشنهيب",
    wilayat: Wilayat.SALALAH,
    area: "أشنهيب",
    type: SchoolType.GOVERNMENT,
    grades: "1-4",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.1100, lng: 54.0000 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8196",
    name: "مدرسة السراج",
    wilayat: Wilayat.SALALAH,
    area: "صلالة",
    type: SchoolType.GOVERNMENT,
    grades: "1-12",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0290, lng: 54.0990 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8197",
    name: "مدرسة خولة بنت حكيم",
    wilayat: Wilayat.SALALAH,
    area: "صلالة",
    type: SchoolType.GOVERNMENT,
    grades: "10-12",
    gender: Gender.GIRLS,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0200, lng: 54.0980 },
    contact: { phone: "23290004" },
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 4
  },
  {
    id: "8199",
    name: "مدرسة الدهاريز",
    wilayat: Wilayat.SALALAH,
    area: "الدهاريز",
    type: SchoolType.GOVERNMENT,
    grades: "1-4",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0370, lng: 54.1220 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },

  // =================================================================
  // مدارس حكومية - ثمريت
  // =================================================================
  {
    id: "8201",
    name: "مدرسة جابر بن حيان",
    wilayat: Wilayat.THUMRAIT,
    area: "ثمريت",
    type: SchoolType.GOVERNMENT,
    grades: "9-12", // Updated from 5-12
    gender: Gender.BOYS,
    shift: Shift.MORNING,
    coordinates: { lat: 17.622583, lng: 54.050453 }, // Exact coords from map link
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8299", // New School Entry
    name: "مدرسة يزيد بن الحارث",
    wilayat: Wilayat.THUMRAIT,
    area: "ثمريت",
    type: SchoolType.GOVERNMENT,
    grades: "5-8",
    gender: Gender.BOYS,
    shift: Shift.EVENING,
    coordinates: { lat: 17.622583, lng: 54.050453 }, // Same location as Jabir bin Hayyan
    contact: { managerName: "هشام الكحالي" },
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 4
  },
  {
    id: "8202",
    name: "مدرسة النعيم",
    wilayat: Wilayat.THUMRAIT,
    area: "ثمريت",
    type: SchoolType.GOVERNMENT,
    grades: "1-4",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.6130, lng: 54.0340 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8203",
    name: "مدرسة ثمريت",
    wilayat: Wilayat.THUMRAIT,
    area: "ثمريت",
    type: SchoolType.GOVERNMENT,
    grades: "5-12",
    gender: Gender.GIRLS,
    shift: Shift.MORNING,
    coordinates: { lat: 17.6100, lng: 54.0300 },
    contact: { phone: "23270001" },
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 4
  },
  {
    id: "8204",
    name: "مدرسة ذهبان",
    wilayat: Wilayat.THUMRAIT,
    area: "ذهبان",
    type: SchoolType.GOVERNMENT,
    grades: "1-4",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.5500, lng: 54.0500 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8205",
    name: "مدرسة مضى",
    wilayat: Wilayat.THUMRAIT,
    area: "مضى",
    type: SchoolType.GOVERNMENT,
    grades: "1-12",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.4000, lng: 53.8000 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8209",
    name: "مدرسة تدهو",
    wilayat: Wilayat.THUMRAIT,
    area: "تدهو",
    type: SchoolType.GOVERNMENT,
    grades: "1-10",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.7000, lng: 54.1000 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8211",
    name: "مدرسة النجد",
    wilayat: Wilayat.THUMRAIT,
    area: "النجد",
    type: SchoolType.GOVERNMENT,
    grades: "1-12",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.8000, lng: 54.2000 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8213",
    name: "مدرسة المطهفة",
    wilayat: Wilayat.THUMRAIT,
    area: "المطهفة",
    type: SchoolType.GOVERNMENT,
    grades: "1-10",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.5000, lng: 53.9000 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8215",
    name: "مدرسة ربكوت",
    wilayat: Wilayat.THUMRAIT,
    area: "ربكوت",
    type: SchoolType.GOVERNMENT,
    grades: "1-12",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.6500, lng: 54.3000 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8217",
    name: "مدرسة الشصر",
    wilayat: Wilayat.THUMRAIT,
    area: "الشصر",
    type: SchoolType.GOVERNMENT,
    grades: "1-12",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 18.2000, lng: 53.6000 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8219",
    name: "مدرسة قتبيت",
    wilayat: Wilayat.THUMRAIT,
    area: "نيابة قتبيت",
    type: SchoolType.GOVERNMENT,
    grades: "1-12",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 19.1600, lng: 54.5000 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8220",
    name: "مدرسة روية",
    wilayat: Wilayat.THUMRAIT,
    area: "روية",
    type: SchoolType.GOVERNMENT,
    grades: "1-12",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.7500, lng: 54.0000 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8223",
    name: "مدرسة عيون",
    wilayat: Wilayat.THUMRAIT,
    area: "عيون",
    type: SchoolType.GOVERNMENT,
    grades: "1-10",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.3500, lng: 53.8500 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8224",
    name: "مدرسة الحشمان",
    wilayat: Wilayat.THUMRAIT,
    area: "الحشمان",
    type: SchoolType.GOVERNMENT,
    grades: "1-10",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 18.0000, lng: 53.0000 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8225",
    name: "مدرسة بيثنة",
    wilayat: Wilayat.THUMRAIT,
    area: "بيثنة",
    type: SchoolType.GOVERNMENT,
    grades: "1-12",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.8500, lng: 54.1500 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8226",
    name: "مدرسة ذهبون",
    wilayat: Wilayat.THUMRAIT,
    area: "ذهبون",
    type: SchoolType.GOVERNMENT,
    grades: "1-12",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.9000, lng: 54.2500 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8227",
    name: "مدرسة بربزوم",
    wilayat: Wilayat.THUMRAIT,
    area: "بربزوم",
    type: SchoolType.GOVERNMENT,
    grades: "5-12",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.5000, lng: 54.1000 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },

  // =================================================================
  // مدارس حكومية - رخيوت
  // =================================================================
  {
    id: "8601",
    name: "مدرسة حيرون",
    wilayat: Wilayat.RAKHYUT,
    area: "جبال رخيوت",
    type: SchoolType.GOVERNMENT,
    grades: "1-12",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 16.7600, lng: 53.3500 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8603",
    name: "مدرسة شرشتي",
    wilayat: Wilayat.RAKHYUT,
    area: "شرشتي",
    type: SchoolType.GOVERNMENT,
    grades: "1-12",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 16.7550, lng: 53.3700 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8605",
    name: "مدرسة رخيوت",
    wilayat: Wilayat.RAKHYUT,
    area: "رخيوت",
    type: SchoolType.GOVERNMENT,
    grades: "1-12",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 16.7450, lng: 53.4050 },
    contact: { phone: "23250001" },
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 4
  },
  {
    id: "8607",
    name: "مدرسة شهب أصعيب للبنين",
    wilayat: Wilayat.RAKHYUT,
    area: "شهب أصعيب",
    type: SchoolType.GOVERNMENT,
    grades: "5-12",
    gender: Gender.BOYS,
    shift: Shift.MORNING,
    coordinates: { lat: 16.7700, lng: 53.3800 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8608",
    name: "مدرسة شهب أصعيب",
    wilayat: Wilayat.RAKHYUT,
    area: "شهب أصعيب",
    type: SchoolType.GOVERNMENT,
    grades: "1-12",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 16.7720, lng: 53.3820 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8609",
    name: "مدرسة أجدروت للبنين",
    wilayat: Wilayat.RAKHYUT,
    area: "أجدروت",
    type: SchoolType.GOVERNMENT,
    grades: "5-12",
    gender: Gender.BOYS,
    shift: Shift.MORNING,
    coordinates: { lat: 16.8000, lng: 53.3000 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8610",
    name: "مدرسة أجدروت",
    wilayat: Wilayat.RAKHYUT,
    area: "أجدروت",
    type: SchoolType.GOVERNMENT,
    grades: "1-12",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 16.8020, lng: 53.3020 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },
  {
    id: "8611",
    name: "مدرسة أرديت",
    wilayat: Wilayat.RAKHYUT,
    area: "أرديت",
    type: SchoolType.GOVERNMENT,
    grades: "1-12",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 16.7900, lng: 53.3300 },
    contact: {},
    source: "وزارة التربية والتعليم",
    isVerified: true,
    qualityScore: 3
  },

  // =================================================================
  // مدارس خاصة ورياض أطفال
  // =================================================================
  {
    id: "P001",
    name: "روضة المدينة الخاصة أحادية اللغة",
    wilayat: Wilayat.SALALAH,
    area: "صلالة الجديدة",
    type: SchoolType.KINDERGARTEN,
    grades: "روضة-تمهيدي",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0100, lng: 54.0800 },
    contact: { managerName: "فاطمة القرشي", phone: "96596366" },
    source: "oman-edu.com",
    isVerified: true,
    qualityScore: 4
  },
  {
    id: "P003",
    name: "روضة جمعية المرأة العمانية صلالة الخاصة",
    wilayat: Wilayat.SALALAH,
    area: "صلالة الجديدة",
    type: SchoolType.KINDERGARTEN,
    grades: "روضة-تمهيدي",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0120, lng: 54.0820 },
    contact: { managerName: "منى الهديبي", phone: "23202570" },
    source: "oman-edu.com",
    isVerified: true,
    qualityScore: 4
  },
  {
    id: "P004",
    name: "مدرسة صلالة الخاصة",
    wilayat: Wilayat.SALALAH,
    area: "السعادة الجنوبية",
    type: SchoolType.PRIVATE,
    grades: "تمهيدي-12",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0500, lng: 54.1500 },
    contact: { managerName: "محمد الواردي", phone: "23226166" },
    source: "oman-edu.com",
    isVerified: true,
    qualityScore: 5
  },
  {
    id: "P005",
    name: "مدرسة فاطمة الزهراء الخاصة",
    wilayat: Wilayat.SALALAH,
    area: "الحصيلة",
    type: SchoolType.PRIVATE,
    grades: "تمهيدي-12",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0250, lng: 54.1100 },
    contact: { managerName: "ناصر البلوشي", phone: "23292699" },
    source: "oman-edu.com",
    isVerified: true,
    qualityScore: 5
  },
  {
    id: "P006",
    name: "مدرسة المعارف الخاصة",
    wilayat: Wilayat.SALALAH,
    area: "الحصيلة",
    type: SchoolType.PRIVATE,
    grades: "تمهيدي-11",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0270, lng: 54.1120 },
    contact: { managerName: "صالح النهار", phone: "23296588" },
    source: "oman-edu.com",
    isVerified: true,
    qualityScore: 5
  },
  {
    id: "P007",
    name: "روضة قاعدة ثمريت الخاصة",
    wilayat: Wilayat.THUMRAIT,
    area: "ثمريت",
    type: SchoolType.KINDERGARTEN,
    grades: "روضة-تمهيدي",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.6150, lng: 54.0350 },
    contact: { managerName: "عزة التيس", phone: "23246446" },
    source: "oman-edu.com",
    isVerified: true,
    qualityScore: 4
  },
  {
    id: "P008",
    name: "مدرسة سهمم الخاصة",
    wilayat: Wilayat.SALALAH,
    area: "الوادي",
    type: SchoolType.PRIVATE,
    grades: "تمهيدي-12",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0300, lng: 54.0700 },
    contact: { managerName: "زينب الشنفري", phone: "23214079" },
    source: "oman-edu.com",
    isVerified: true,
    qualityScore: 5
  },
  {
    id: "P009",
    name: "مدرسة الأنوار الخاصة",
    wilayat: Wilayat.SALALAH,
    area: "الوادي",
    type: SchoolType.PRIVATE,
    grades: "تمهيدي-12",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0320, lng: 54.0720 },
    contact: { managerName: "سمير محمد نصر", phone: "23294446" },
    source: "oman-edu.com",
    isVerified: true,
    qualityScore: 5
  },
  {
    id: "P010",
    name: "مدرسة ريدان الخاصة (عوقد)",
    wilayat: Wilayat.SALALAH,
    area: "عوقد الشمالية",
    type: SchoolType.PRIVATE,
    grades: "تمهيدي-4",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0310, lng: 54.0510 },
    contact: { managerName: "سمير محمد القاضي", phone: "23214178" },
    source: "oman-edu.com",
    isVerified: true,
    qualityScore: 5
  },
  {
    id: "P011",
    name: "مدرسة ريدان الخاصة (5-12)",
    wilayat: Wilayat.SALALAH,
    area: "عوقد الشمالية",
    type: SchoolType.PRIVATE,
    grades: "5-12",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0330, lng: 54.0530 },
    contact: { managerName: "علي برعي", phone: "23213716" },
    source: "oman-edu.com",
    isVerified: true,
    qualityScore: 5
  },
  {
    id: "P012",
    name: "مدرسة الجوهرة الخاصة",
    wilayat: Wilayat.SALALAH,
    area: "شمال المؤتين",
    type: SchoolType.PRIVATE,
    grades: "تمهيدي-4",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0600, lng: 54.1200 },
    contact: { managerName: "ميرزا اليافي", phone: "23212289" },
    source: "oman-edu.com",
    isVerified: true,
    qualityScore: 5
  },
  {
    id: "P013",
    name: "مدرسة الماهل الخاصة (بنين)",
    wilayat: Wilayat.SALALAH,
    area: "الدهاريز الشمالية",
    type: SchoolType.PRIVATE,
    grades: "1-12",
    gender: Gender.BOYS,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0400, lng: 54.1250 },
    contact: { managerName: "كمال عبدالله", phone: "23235813" },
    source: "oman-edu.com",
    isVerified: true,
    qualityScore: 5
  },
  {
    id: "P014",
    name: "مدرسة نور العلم الخاصة",
    wilayat: Wilayat.THUMRAIT,
    area: "ثمريت",
    type: SchoolType.PRIVATE,
    grades: "1-10",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.6120, lng: 54.0320 },
    contact: { managerName: "ثنات نيل", phone: "23278132" },
    source: "oman-edu.com",
    isVerified: true,
    qualityScore: 5
  },
  {
    id: "P015",
    name: "روضة التقوى الخاصة",
    wilayat: Wilayat.SALALAH,
    area: "الوادي",
    type: SchoolType.KINDERGARTEN,
    grades: "روضة-تمهيدي",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0290, lng: 54.0690 },
    contact: { managerName: "اسيا بيت وقنفي", phone: "23290454" },
    source: "oman-edu.com",
    isVerified: true,
    qualityScore: 4
  },
  {
    id: "P017",
    name: "مدرسة الضياء الخاصة",
    wilayat: Wilayat.SALALAH,
    area: "صلالة الجديدة",
    type: SchoolType.PRIVATE,
    grades: "تمهيدي-12",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0110, lng: 54.0810 },
    contact: { managerName: "أنيسة محمد", phone: "95882848" },
    source: "oman-edu.com",
    isVerified: true,
    qualityScore: 5
  },
  {
    id: "P020",
    name: "روضة مجد ظفار الخاصة",
    wilayat: Wilayat.SALALAH,
    area: "السعادة الشمالية",
    type: SchoolType.KINDERGARTEN,
    grades: "روضة-تمهيدي",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0560, lng: 54.1520 },
    contact: { managerName: "منى صباح", phone: "98122466" },
    source: "oman-edu.com",
    isVerified: true,
    qualityScore: 4
  },
  {
    id: "P021",
    name: "روضة براعم ظفار الخاصة",
    wilayat: Wilayat.SALALAH,
    area: "السعادة الجنوبية",
    type: SchoolType.KINDERGARTEN,
    grades: "روضة-تمهيدي",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0520, lng: 54.1480 },
    contact: { managerName: "منى النجيمي", phone: "95434606" },
    source: "oman-edu.com",
    isVerified: true,
    qualityScore: 4
  },
  {
    id: "P022",
    name: "مدرسة الماهل الخاصة (بنات)",
    wilayat: Wilayat.SALALAH,
    area: "الدهاريز الشمالية",
    type: SchoolType.PRIVATE,
    grades: "تمهيدي-8",
    gender: Gender.GIRLS,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0410, lng: 54.1260 },
    contact: { managerName: "جمال فتحي", phone: "23235447" },
    source: "oman-edu.com",
    isVerified: true,
    qualityScore: 5
  },
  {
    id: "P023",
    name: "مدرسة مروج ظفار الخاصة",
    wilayat: Wilayat.SALALAH,
    area: "السعادة",
    type: SchoolType.PRIVATE,
    grades: "تمهيدي-4",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0540, lng: 54.1510 },
    contact: { managerName: "اميرة شوقي", phone: "93828729" },
    source: "oman-edu.com",
    isVerified: true,
    qualityScore: 4
  },
  {
    id: "P024",
    name: "مدرسة صلالة العالمية",
    wilayat: Wilayat.SALALAH,
    area: "السعادة",
    type: SchoolType.PRIVATE,
    grades: "تمهيدي-12",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0530, lng: 54.1530 },
    contact: { managerName: "رادا كريشان", phone: "23230300" },
    source: "oman-edu.com",
    isVerified: true,
    qualityScore: 5
  },
  {
    id: "P025",
    name: "المدرسة العالمية",
    wilayat: Wilayat.SALALAH,
    area: "السعادة",
    type: SchoolType.PRIVATE,
    grades: "تمهيدي-6",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0525, lng: 54.1525 },
    contact: { managerName: "سدار بوسعه", phone: "23235492" },
    source: "oman-edu.com",
    isVerified: true,
    qualityScore: 4
  },
  {
    id: "P026",
    name: "مدرسة براعم صلالة الخاصة",
    wilayat: Wilayat.SALALAH,
    area: "عوقد الشمالية",
    type: SchoolType.PRIVATE,
    grades: "تمهيدي-6",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0340, lng: 54.0520 },
    contact: { managerName: "محمد طه", phone: "23210872" },
    source: "oman-edu.com",
    isVerified: true,
    qualityScore: 5
  },
  {
    id: "P027",
    name: "روضة أطفال عمان الخاصة",
    wilayat: Wilayat.SALALAH,
    area: "السعادة الشمالية",
    type: SchoolType.KINDERGARTEN,
    grades: "روضة-تمهيدي",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0570, lng: 54.1540 },
    contact: { managerName: "شريفة البلوشي", phone: "23233010" },
    source: "oman-edu.com",
    isVerified: true,
    qualityScore: 4
  },
  {
    id: "P028",
    name: "مدرسة أجيال ثمريت الخاصة",
    wilayat: Wilayat.THUMRAIT,
    area: "ثمريت",
    type: SchoolType.PRIVATE,
    grades: "تمهيدي-4",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.6140, lng: 54.0330 },
    contact: { managerName: "yاسمين ربيح", phone: "23278456" },
    source: "oman-edu.com",
    isVerified: true,
    qualityScore: 5
  },
  {
    id: "P029",
    name: "مدرسة أحلام الطفولة الخاصة",
    wilayat: Wilayat.SALALAH,
    area: "صلالة الجديدة",
    type: SchoolType.PRIVATE,
    grades: "تمهيدي-4",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0130, lng: 54.0830 },
    contact: { managerName: "رضا جمال", phone: "98021200" },
    source: "oman-edu.com",
    isVerified: true,
    qualityScore: 4
  },
  {
    id: "P030",
    name: "مدرسة رواد العلم العالمية",
    wilayat: Wilayat.SALALAH,
    area: "الدهاريز",
    type: SchoolType.PRIVATE,
    grades: "تمهيدي-6",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0390, lng: 54.1240 },
    contact: { managerName: "جولييت جون", phone: "23235484" },
    source: "oman-edu.com",
    isVerified: true,
    qualityScore: 5
  },
  {
    id: "P031",
    name: "روضة زاهر الربيع الخاصة",
    wilayat: Wilayat.SALALAH,
    area: "السعادة الجنوبية",
    type: SchoolType.KINDERGARTEN,
    grades: "روضة-تمهيدي",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0510, lng: 54.1490 },
    contact: { managerName: "هدى الشنفري", phone: "23227650" },
    source: "oman-edu.com",
    isVerified: true,
    qualityScore: 4
  },
  {
    id: "P032",
    name: "مدرسة فتححات الخاصة",
    wilayat: Wilayat.SALALAH,
    area: "صلالوت",
    type: SchoolType.PRIVATE,
    grades: "تمهيدي-4",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0240, lng: 54.0940 }, // approximate
    contact: { managerName: "إيمان الزرقاني", phone: "93943095" },
    source: "oman-edu.com",
    isVerified: true,
    qualityScore: 4
  },
  {
    id: "P033",
    name: "مدرسة العقول النيرة الخاصة",
    wilayat: Wilayat.SALALAH,
    area: "صلالوت",
    type: SchoolType.PRIVATE,
    grades: "تمهيدي-4",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0245, lng: 54.0945 }, // approximate
    contact: { managerName: "ركاب قطب", phone: "23249972" },
    source: "oman-edu.com",
    isVerified: true,
    qualityScore: 4
  },
  {
    id: "P034",
    name: "مدرسة البادية الخاصة",
    wilayat: Wilayat.SALALAH,
    area: "صلالوت",
    type: SchoolType.PRIVATE,
    grades: "تمهيدي-4",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0250, lng: 54.0950 }, // approximate
    contact: { managerName: "داليا أبو غنيه", phone: "71504452" },
    source: "oman-edu.com",
    isVerified: true,
    qualityScore: 4
  },
  {
    id: "P035",
    name: "مدرسة الزان الربيع الخاصة",
    wilayat: Wilayat.SALALAH,
    area: "عوقد",
    type: SchoolType.PRIVATE,
    grades: "تمهيدي-2",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0320, lng: 54.0520 },
    contact: { managerName: "نور سالني", phone: "23229533" },
    source: "oman-edu.com",
    isVerified: true,
    qualityScore: 4
  },
  {
    id: "P036",
    name: "مدرسة نور ظفار الخاصة",
    wilayat: Wilayat.SALALAH,
    area: "عوقد",
    type: SchoolType.PRIVATE,
    grades: "روضة-تمهيدي",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0315, lng: 54.0515 },
    contact: { managerName: "شيخة كوان", phone: "23229505" },
    source: "oman-edu.com",
    isVerified: true,
    qualityScore: 4
  },
  {
    id: "P037",
    name: "مدرسة سمهرم الخاصة",
    wilayat: Wilayat.SALALAH,
    area: "السعادة",
    type: SchoolType.PRIVATE,
    grades: "تمهيدي-12",
    gender: Gender.MIXED,
    shift: Shift.MORNING,
    coordinates: { lat: 17.0545, lng: 54.1515 },
    contact: { managerName: "صالح بشر", phone: "99092556" },
    source: "oman-edu.com",
    isVerified: true,
    qualityScore: 5
  }
];